//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_QLSCV
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATHUE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATHUE()
        {
            this.CHITIETDATSANs = new HashSet<CHITIETDATSAN>();
            this.TINHTRANGSANs = new HashSet<TINHTRANGSAN>();
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
        }
    
        public int MaCaThue { get; set; }
        public Nullable<int> Gia { get; set; }
        public Nullable<int> MaSan { get; set; }
        public Nullable<int> MaCa { get; set; }
    
        public virtual CA CA { get; set; }
        public virtual SAN SAN { get; set; }
        public virtual TINHTRANGSAN TINHTRANGSAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATSAN> CHITIETDATSANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TINHTRANGSAN> TINHTRANGSANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
    }
}
