//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_QLSCV
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public int MaHD { get; set; }
        public string ThoiGianThanhToan { get; set; }
        public string HoTenNguoiTT { get; set; }
        public string NhanVienTT { get; set; }
        public string TongTien { get; set; }
        public Nullable<int> MaPhieu { get; set; }
    
        public virtual PHIEUDATSAN PHIEUDATSAN { get; set; }
    }
}
